#pragma once



LPCWSTR LSTRW(int i);

enum {
	RID_UNK,
	RID_DestFileExist,
	RID_DestEmpty,
	RID_SuffixNotSupported,
	RID_UnkSourceSize,
	RID_SetExcludeRangeError,
	RID_SetRangeError,
	RID_ConvertorNotFound,
	RID_InitBufferFailed,
	RID_CreateDestFailed,
	RID_CreateWorkerProcessError,
	RID_CreateWorkerThreadError,
	RID_GetNextRangeError,
	RID_SetSourceFilePointerFaied,
	RID_ReadSourceFaied,
	RID_UnexpectedEOF,
	RID_WriteFileError,

	RID_error,
	RID_nodisks,
	RID_Disk,
	RID_BusType,
	RID_Size,
	RID_ChooseDisk,
	RID_InvalidInput,
	RID_NoPartitions,
	RID_partition,
	RID_label,
	RID_Usage,
	RID_1stsector,
	RID_InputPartNumbersToBeExcluded,
	RID_OpenSourceError,
	RID_InvalidPartNum,
	RID_ExcludedParts,
	RID_SetOutputPath,
	RID_SetImageOptions,
	RID_OnStart,
	RID_ConvertorThreadError,
	RID_ErrorInfo,
	RID_ConvertorError,
	RID_GOOD,

	RID_ConnectingHostPort,
	RID_Failed_retry_5_seconds_later,
	RID_drcmd_query_pc_info,
	RID_drcmd_query_disk_info,
	RID_drcmd_open_disk,
	RID_drcmd_seek_disk,
	RID_drcmd_read_disk,
	RID_drcmd_open_volume,
	RID_drcmd_read_volume,

	RID_Partdlg_Title,
	RID_PartIndex,
	RID_Lable,
	RID_PartUsed,
	RID_SectorOffset,
	RID_Bitlocker,
	RID_Option_All_Space,
	RID_Option_VSS,

	RID_DiskNum,
	RID_OtherInfo,

	RID_Disk_Remotely_Tip1,
	RID_Disk_Remotely_NoDisks,
	RID_Disk_Remotely_Unexpect,
	RID_Disk_Remotely_Error,

	RID_Disk_Locally_Tip1,
	RID_Disk_Locally_NoDisks,
	RID_Disk_GetList,
	RID_Disk_GetListFailed,
	RID_Disk_RemotelyGetList,
	RID_Disk_RemotelyGetListFailed,
	RID_Disk_ConnectFailed,
	RID_Disk_GetRemoteHostInfoFailed,
	RID_Disk_GetRemoteDiskInfoFailed,

	RID_MakingImageDD,
	RID_MakingImage,

	RID_Part_NotConfig,
	RID_Part_FileExist,
	RID_Part_expect_unlock,
	RID_Part_bitlock_unexpected,

	RID_UnableToEstOutputSize,
	RID_TIPS,
	RID_DiskConfigError,
	RID_ImageOutputWarning1,
	RID_ImageOutputWarning2,
	RID_ImageOutputWarning3,
	RID_NoDisksChecked,
	RID_ImageTaskStarted,
	RID_SureToStop,
	RID_PreparingCloneNext,
	RID_WaitForCompletion,
	RID_ErrorString,
	RID_OpenVolErrorComma,
	RID_ShouldRunX64Version,
	RID_OpenVSSVolFailed,
	RID_GetVSSVolPathFailed,
	RID_ImagePathNotSet,
	RID_GettingStarted,
	RID_Speed_Remaining,
	RID_ImageMaker_End_OK,
	RID_ImageMaker_End_Err,
	RID_VSS_init,
	RID_VSS_init_err,
	RID_VSS_BeforeStartSnapshot,
	RID_VSS_StartSnapshotErr,
	RID_VSS_AddVol,
	RID_VSS_AddVolErr,
	RID_VSS_BeforeMakeSnapshot,
	RID_VSS_MakeSnapshotErr,
	RID_VSS_SnapshotDone,
		RID_SaveFileDlgTitle,
		RID_FileExistAndDelFailed,
		RID_InvalidFileExt,
		RID_NotAllowedChar,
		RID_insufficient_diskspace_for_rawimg,
		RID_uncheck_part_warning1,
		RID_uncheck_part_warning2,
		RID_disk_config_exmode_excluded_parts,
		RID_disk_config_exmode_onlyused,
		RID_disk_config_exmode_allspace,

};